version: "3"

services:
  verifier:
    depends_on:
      - l1_chain
      - deployer
    image: ethereumoptimism/verifier
    build:
      context: ..
      dockerfile: ./ops/docker/Dockerfile.geth
    # override with the geth script and the env vars required for it
    entrypoint: sh ./geth.sh
    env_file:
      - ./envs/geth.env
    environment:
        ETH1_HTTP: http://l1_chain:8545
        ROLLUP_STATE_DUMP_PATH: http://deployer:8081/state-dump.latest.json
        # used for getting the addresses
        URL: http://deployer:8081/addresses.json
        # connecting to the DTL
        # TODO(annieke): should this be different for verifier?
        ROLLUP_CLIENT_HTTP: http://dtl:7878
        ETH1_CTC_DEPLOYMENT_HEIGHT: 8
        RETRIES: 60
        IS_VERIFIER: true
    ports:
      - ${VERIFIER_HTTP_PORT:-8545}:8545
      - ${VERIFIER_WS_PORT:-8546}:8546